---
# tasks file for pi-hole
  - name: Creates directory
    file:
      path: "{{item }}"
      state: directory
    loop:
      - "{{docker_folder}}/{{pihole_container_name}}"

  - name: Generate docker_compose
    template:
      src: "docker_compose.j2"
      dest: "{{docker_folder}}/{{pihole_container_name}}/docker-compose.yml"
    notify: Restart {{pihole_container_name}} container

  - name: Generate init
    template:
      src: "docker_compose_service.j2"
      dest: "/etc/systemd/system/{{pihole_container_name}}.service"
    notify: Restart {{pihole_container_name}} container
